plugins {
    id 'java'
    //   id "io.freefair.lombok" version "8.13.1"
    id "io.qameta.allure" version "2.12.0"
}

group = 'ru.vol'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation(
            "org.junit.jupiter:junit-jupiter",
            "io.rest-assured:rest-assured:5.5.1",
            "com.fasterxml.jackson.core:jackson-databind:2.18.2",
            "org.assertj:assertj-core:3.24.2",
            "io.qameta.allure:allure-rest-assured:2.29.1"
    )
}

test {
    useJUnitPlatform()
}